# Generated by Django 5.0.6 on 2024-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_course_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='Unknown Faculty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_name',
            field=models.CharField(default='Unknown Duration', max_length=255),
            preserve_default=False,
        ),
    ]
